### ISSUE TITLE
How to add an image for the Chrome Extension???

### ISSUE THREAD

**Issue by royalhope** [WebDevSimplified/Coronavirus-Chrome-Extension#3]
Hey Kyle, I am able to make the Chrome extension, but unable to find the answer for adding an image for the Extension. any inputs?

**Comment by merajjahir** [comment]
_@royalhope , if you didn't find the answer by now, you need to add **"icon"** tag in you manifest file_ 
something like this: 
```"icons": { "128": "your_icon_name.png" },```

## you may check out -> [Google chrome developers docs](https://developer.chrome.com/docs/extensions/mv2/manifest/icons/)

**Comment by royalhope** [comment]
@merajjahir, thanks for your help, i fixed the issue a couple months back using the same snippet you shared, still thanks for your help.
